apiVersion: v1
kind: Service
metadata:
  name: golang-record-service
spec:
  selector:
    app: golang-record
  ports:
    - name: golang
      port: 98
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  # LoadBanlancer: 负载均衡