// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"golang/internal/repository"
	"golang/internal/repository/dao"
	"golang/internal/service"
	"golang/internal/web"
	"golang/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitGinMiddleware()
	db := ioc.InitDB()
	languagesDao := dao.NewLanguageDao(db)
	languageRepository := repository.NewLanguageRepository(languagesDao)
	languagesService := service.NewLanguagesService(languageRepository)
	languagesHandler := web.NewLanguageHandler(languagesService)
	engine := ioc.InitWebServer(v, languagesHandler)
	return engine
}
