// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"golang/internal/repository"
	"golang/internal/repository/dao"
	"golang/internal/service"
	"golang/internal/web"
	"golang/internal/web/ijwt"
	"golang/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	db := InitDB()
	cmdable := InitRedis()
	handler := ijwt.NewRedisJwtHandler(cmdable)
	v := ioc.InitGinMiddleware(db, handler)
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	usersHandler := web.NewUserHandler(userService, handler)
	engine := ioc.InitWebServer(v, usersHandler)
	return engine
}
